# Generated by Django 3.0.6 on 2021-07-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image_file',
            field=models.ImageField(default='', upload_to='tracker/images'),
        ),
        migrations.AddField(
            model_name='link',
            name='image_url',
            field=models.URLField(default=''),
        ),
    ]
