# Generated by Django 3.0.6 on 2021-07-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210706_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='image_file',
        ),
    ]
