# Generated by Django 3.0.6 on 2021-07-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_link_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
