# Generated by Django 3.0.6 on 2021-07-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20210706_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='deal',
            field=models.BooleanField(default=None),
        ),
    ]
