# Generated by Django 3.0.6 on 2021-07-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_link_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='deal',
            field=models.BooleanField(default='None'),
        ),
    ]
