# Generated by Django 3.0.6 on 2021-07-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20210706_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='deal',
            field=models.BooleanField(blank=True),
        ),
    ]
